[pytest]
addopts = -s -v
python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
    regression: all tests related to regression
    smoke: all tests related to smoke
    registration: all tests related to registration
    authorization: all tests related to authorization