from enum import Enum

class AllureTags(str, Enum):
    COURSES = "COURSES"
    DASHBOARD = "DASHBOARD"
    USER_LOGIN = "USER_LOGIN"
    NAVIGATION = "NAVIGATION"
    REGISTRATION = "REGISTRATION"
    REGRESSION = "REGRESSION"
    AUTHORIZATION = "AUTHORIZATION"